#Problem link:
# https://leetcode.com/problems/students-and-examinations/description/?envType=study-plan-v2&envId=top-sql-50

# Write your MySQL query statement below

SELECT S.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS S
JOIN SUBJECTS SUB
LEFT JOIN EXAMINATIONS E
ON S.STUDENT_ID=E.STUDENT_ID
AND SUB.SUBJECT_NAME= E.SUBJECT_NAME
GROUP BY S.STUDENT_ID, SUB.SUBJECT_NAME
ORDER BY STUDENT_ID ASC, SUBJECT_NAME ASC;
